### ISSUE TITLE
Implement 2D circular buffer

### ISSUE THREAD

**Issue by poornack** [uvic-auvic/firmware#7]
**Problem Description:** A two dimensional FIFO circular buffer required to buffer incoming UART messages.

**Task:** Write and unit test a two dimensional circular buffer. This should be modular enough to use on different components. Use component specific files if necessary. Follow the below API:

**Layout:**
A 2D buffer with n slots each with m bytes

| Slot 1 | Slot 2           | ...  | Slot n |
| :-------------: |:-------------:| :-----:|:------:|
| Byte 1      | Byte 1    | Byte 1   | Byte 1   |
| Byte 2      | Byte 2|   Byte 2 | Byte 2 |
| ... | ...    |    ... | ... |
| Byte m | Byte m | Byte m | Byte m|

**API:**

`uint8_t circBuffer2D_getSpaceAvailable(const circBuffer2D_channel_E channel);`
Returns the number of slots available. This is not the number of bytes available in the buffer. Function returns 0 if `channel` is not a valid channel.

`bool circBuffer2D_push(const circBuffer2D_channel_E channel, uint8_t const * const data, const uint16_t length);`
Add the data in the array `data` to the first open slot. The parameter `length` indicates the size of `data` in bytes. Function returns true if added successfully. Function returns false if `channel` is not a valid channel, `data` is NULL, `size` is 0, `size` is greater than the size of one slot (m) or if no slots are available in the buffer.

`uint8_t circBuffer2D_pop(const circBuffer2D_channel_E channel, uint8_t * const dataToReturn);`
Copy the oldest slot in the buffer into `dataToReturn` and return the size of the data copied. Function returns 0 if `channel` is not a valid channel or if the buffer is empty.

**Comment by poornack** [comment]
@cartercooper

**Comment by cartercooper** [comment]
Created functional circular 2D buffer to the specifications described in the respective issue.

Tested:

Creating and manipulating multiple channels.
Filling the buffer all the way then attempting to overfill the buffer, emptying all the way then attempting to pop an empty buffer.
Checking space available for both full and empty cases (working for all cases in between full and empty as well but not tested in this version of the test file.
Consistency of pushed and popped data.
Causes seg fault when trying to push into last slot of buffer when buffer is 5x5, so all testing was moved to 8x8 buffer and the problem was solved.
